package com.company;

public class Main {

    public static void main(String[] args) {

        String patientName = "Stacey Manson";
        boolean hasInsurance =false;
        int temp = 102;
        float numVisits = 5.02f;
        float copay = 150.5f;
        String nxtappt = "September 17, 2020";
        String cn = "734-427-9984";


        System.out.println("Patient Details:");
        System.out.println("Name: " + patientName);
        System.out.println("Patient has insurance: " + hasInsurance);
        System.out.println("Body temperature: " + temp);
        System.out.println("Number of visits: " + numVisits);
        System.out.println("Copay Amount " + copay);
        System.out.println("Next Appointment: " + nxtappt);
        System.out.println("Contact Number: " + cn);




    }
}
